version: '3'

services:
  # ctn-konoha-database:
  #   container_name: ctn-konoha-database
  #   build: ./database/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - konoha-network

  # ctn-konoha-api: 
  #   container_name: ctn-konoha-api
  #   build: ./api-node/
  #   command: yarn dev
  #   environment:
  #     NODE_ENV: developent 
  #     DB_HOST: ctn-konoha-database
  #   ports:
  #     - "3333:3333"
  #   restart: always 
  #   depends_on:
  #     - ctn-konoha-database
  #   networks:
  #     - konoha-network
  #   volumes:
  #     - ./api-node/src/:/app/src/

  ctn-konoha-web: 
    container_name: ctn-konoha-web
    build: ./web/
    command: yarn start
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "3000:3000"
    restart: always 
    volumes:
      - ./web/src/:/app/src/

networks:
  konoha-network: 
    driver: bridge